### ISSUE TITLE
Update link to Medium article

### ISSUE THREAD

**Issue by farant** [zekedroid/react-lru#2]
I think you used the link to edit the article in `README.md` instead of https://medium.com/@zekeschmois/rendering-react-elements-into-infinite-scrollable-tables-using-least-recently-used-lru-cache-23d6a8624d45

Thought Medium wouldn't let me read articles any more without creating an account for a second! Lol

**Comment by zekedroid** [comment]
Good catch :) thanks! All fixed now.
